import type {BusinessEvent,OutcomeClaim} from "@/lib/domain/business-event";
import type {CaseStatus} from "@/lib/domain/delivery";
import {workspaceKindStore} from "@/lib/memory/workspace";
import {interviewGrowthDemo} from "./demo-data";
import {writeBusinessMemory} from "./repository";
import {defaultServiceStages} from "./services";
import type {BusinessMemoryModel,EvidenceType,GrowthAction,GrowthActionChannel,GrowthPlan,ServiceCase,CustomerEntity,BusinessEvidence,BusinessService,ServiceChannel} from "./model";

const demoVersionKey="bewater_interview_mock_version";
function normalizeCustomerName(name:string){return name.trim().replace(/\s+/g," ").toLocaleLowerCase();}

export function isDemoEnabled() {
  return workspaceKindStore.read()==="demo"&&interviewGrowthDemo.enabledByDefault;
}

export function shouldSeedDemoWorkspace(model:BusinessMemoryModel) {
  if (!isDemoEnabled()) return false;
  const demoMissing = !model.services.some((service) => service.id === "demo-service-interview");
  if (typeof window === "undefined") return demoMissing;
  return demoMissing || localStorage.getItem(demoVersionKey) !== String(interviewGrowthDemo.version);
}

export function seedDemoWorkspace() {
  const now = new Date().toISOString();
  const customerId = "demo-customer-xiaoyu";
  const serviceId = "demo-service-interview";
  const caseId = "demo-case-yitiao";
  const feedbackCaseId = "demo-case-linyan";
  const stages = defaultServiceStages.map((stage) => ({...stage}));
  const event = (id:string,type:EvidenceType,content:string,summary:string,businessEvents:BusinessEvent[],outcomeClaims:OutcomeClaim[] = []):BusinessEvidence => ({id,type,stageId:`stage-${type}`,content,createdAt:now,extractionStatus:"ready",extractionSummary:summary,detectedSourceKind:type === "conversation" ? "chat" : type === "delivery" ? "meeting_transcript" : "chat",extractedFacts:[],identityCandidates:id === "demo-inquiry" ? [{displayName:"一条",source:"微信",role:"customer",confidence:.94,evidence:"一条：我工作两年了，但面试一追问项目就讲不清楚",proposedCustomerId:customerId,needsConfirmation:false},{displayName:"小鱼",source:"腾讯会议",role:"customer",confidence:.96,evidence:"会议参会人：小鱼",proposedCustomerId:customerId,needsConfirmation:false}] : [],businessEvents,outcomeClaims,caseStatusProposals:[],extractionVersion:"demo-evidence-v1"});
  const inquiry = event("demo-inquiry","conversation","一条：我工作两年了，但面试一追问项目细节就不知道怎么讲。想约一次模拟面试，周三晚上可以吗？\n我：可以，主要会围绕你的项目经历深挖，结束后给你表达建议。","客户因项目表达困难咨询并预约模拟面试。",[{type:"lead_created",title:"产生模拟面试咨询",summary:"客户明确表达项目被追问时难以回答。",occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.98,evidence:["一追问项目细节就不知道怎么讲"],nextActions:["确认模拟面试时间"]},{type:"booking_confirmed",title:"确认模拟面试预约",summary:"双方确认周三晚上进行服务。",occurredAt:now,scheduledStartAt:now,scheduledEndAt:null,confidence:.92,evidence:["想约一次模拟面试，周三晚上可以吗"],nextActions:["客户发送简历与项目材料"]}]);
  const delivery = event("demo-delivery","delivery","腾讯会议参会人：小鱼。面试官围绕项目背景、个人职责、技术取舍和业务结果连续追问。小鱼在个人贡献和结果量化部分多次停顿。复盘时重新组织为：问题—行动—取舍—结果。","交付重点是深挖项目并定位表达短板。",[{type:"delivery_started",title:"开始模拟面试",summary:"围绕真实项目进行连续追问。",occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.98,evidence:["围绕项目背景、个人职责、技术取舍和业务结果连续追问"],nextActions:[]},{type:"delivery_completed",title:"完成项目表达诊断",summary:"定位个人贡献与结果量化两项表达短板，并给出重组方法。",occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.98,evidence:["在个人贡献和结果量化部分多次停顿","重新组织为：问题—行动—取舍—结果"],nextActions:["按新结构重写项目介绍"]}],[{theme:"项目表达",statement:"客户在项目贡献和结果量化上存在明确表达短板。",verification:"observed",confidence:.96,evidence:"在个人贡献和结果量化部分多次停顿"}]);
  const feedback = event("demo-feedback","feedback","小鱼：这次最有帮助的不是模拟了一遍题，而是你一直追问项目，让我发现之前根本没讲清自己的贡献。现在知道该按什么结构准备了。","客户确认核心收获是项目深挖和表达结构。",[{type:"feedback_received",title:"收到客户反馈",summary:"客户将核心收获归因于项目深挖和表达结构。",occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.99,evidence:["发现之前根本没讲清自己的贡献","知道该按什么结构准备了"],nextActions:["一周后回访面试进展"]}],[{theme:"项目表达",statement:"项目深挖帮助客户发现表达短板并明确准备结构。",verification:"self_reported",confidence:.99,evidence:"最有帮助的不是模拟了一遍题，而是你一直追问项目"}]);
  const secondFeedback = event("demo-feedback-linyan","feedback","林言：以前总以为多刷题就行，这次把项目追问一遍，才发现业务结果和个人贡献都说得太虚。","另一位客户也反馈项目追问暴露了表达问题。",[{type:"feedback_received",title:"收到第二位客户反馈",summary:"第二个独立案例再次出现项目贡献表达问题。",occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.98,evidence:["业务结果和个人贡献都说得太虚"],nextActions:[]}],[{theme:"项目表达",statement:"项目追问暴露业务结果与个人贡献表达不足。",verification:"self_reported",confidence:.98,evidence:"业务结果和个人贡献都说得太虚"}]);
  const record = (id:string) => interviewGrowthDemo.records.find((entry) => entry.id === id)!;
  const simpleEvidence = (id:string,type:EvidenceType,eventType:BusinessEvent["type"],title:string,verification?:OutcomeClaim["verification"]) => {const source=record(id); return event(id,type,source.rawText,source.summary,[{type:eventType,title,summary:source.summary,occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.96,evidence:source.evidence,nextActions:[]}],verification?[{theme:"项目表达",statement:source.summary,verification,confidence:.94,evidence:source.evidence[0]}]:[]);};
  const zhouInquiry=simpleEvidence("demo-inquiry-zhou","conversation","lead_created","小红书内容带来咨询");
  const chenFeedback=simpleEvidence("demo-feedback-chen","feedback","feedback_received","收到项目表达反馈","self_reported");
  const suOutcome=simpleEvidence("demo-outcome-su","feedback","feedback_received","真实面试结果回流","verified");
  const fangReferral=simpleEvidence("demo-referral-fang","conversation","booking_confirmed","转介绍带来预约");
  const xuLost=simpleEvidence("demo-lost-xu","conversation","lead_created","识别不匹配咨询");
  const demoCase=(id:string,customer:string,customerId:string,date:string,status:CaseStatus,evidence:BusinessEvidence[],channel?:ServiceChannel):ServiceCase=>({id,customer,customerId,purchaseNumber:1,occurredAt:date,createdAt:now,status,stages,materials:[],discoveryChannel:channel,transactionChannel:status.commercial==="closed"?channel:undefined,evidence});
  const closedReported:CaseStatus={commercial:"closed",delivery:"accepted",payment:"paid",outcome:"reported",updatedAt:now};
  const channels:ServiceChannel[]=[{id:"demo-xianyu",platform:"xianyu",status:"active",launchedAt:"2026-03-01"},{id:"demo-xhs",platform:"xiaohongshu",status:"testing",launchedAt:"2026-05-15"},{id:"demo-wechat",platform:"wechat",status:"active"}];
  const service:BusinessService = {id:serviceId,name:interviewGrowthDemo.service.name,description:interviewGrowthDemo.service.description,pricingMode:"session",price:interviewGrowthDemo.service.price,effortMinutes:interviewGrowthDemo.service.effortMinutes,turnaroundDays:0,channels,stages,createdAt:now,updatedAt:now,cases:[demoCase(caseId,"小鱼",customerId,"2026-07-22",closedReported,[inquiry,delivery,feedback],channels[0]),demoCase(feedbackCaseId,"林言","demo-customer-linyan","2026-07-18",closedReported,[secondFeedback],channels[2]),demoCase("demo-case-zhou","周然","demo-customer-zhou","2026-07-16",{commercial:"lead",delivery:"not_started",payment:"unknown",outcome:"unknown",updatedAt:now},[zhouInquiry],channels[1]),demoCase("demo-case-chen","陈默","demo-customer-chen","2026-06-28",closedReported,[chenFeedback],channels[0]),demoCase("demo-case-su","苏晴","demo-customer-su","2026-06-12",{...closedReported,outcome:"verified"},[suOutcome],channels[2]),demoCase("demo-case-fang","方屿","demo-customer-fang","2026-07-24",{commercial:"booked",delivery:"not_started",payment:"pending",outcome:"unknown",updatedAt:now},[fangReferral],channels[2]),demoCase("demo-case-xu","许澄","demo-customer-xu","2026-05-20",{commercial:"cancelled",delivery:"not_started",payment:"unknown",outcome:"unknown",updatedAt:now},[xuLost],channels[0])]};
  const resumeEvidence=(id:string,type:EvidenceType,eventType:BusinessEvent["type"],title:string,verification?:OutcomeClaim["verification"])=>{const source=record(id);return event(id,type,source.rawText,source.summary,[{type:eventType,title,summary:source.summary,occurredAt:now,scheduledStartAt:null,scheduledEndAt:null,confidence:.96,evidence:source.evidence,nextActions:[]}],verification?[{theme:"简历价值表达",statement:source.summary,verification,confidence:.95,evidence:source.evidence[0]}]:[]);};
  const resumeChannels:ServiceChannel[]=[{id:"demo-resume-xianyu",platform:"xianyu",status:"active",launchedAt:"2026-02-10"},{id:"demo-resume-wechat",platform:"wechat",status:"active"}];
  const resumeService:BusinessService={id:"demo-service-resume",name:interviewGrowthDemo.secondaryService.name,description:interviewGrowthDemo.secondaryService.description,pricingMode:"package",price:interviewGrowthDemo.secondaryService.price,effortMinutes:interviewGrowthDemo.secondaryService.effortMinutes,turnaroundDays:2,channels:resumeChannels,stages,createdAt:now,updatedAt:now,cases:[demoCase("demo-resume-case-xiaoman","小满","demo-customer-xiaoman","2026-07-20",{commercial:"booked",delivery:"preparing",payment:"paid",outcome:"unknown",updatedAt:now},[resumeEvidence("demo-resume-inquiry-xiaoman","conversation","booking_confirmed","确认简历优化需求")],resumeChannels[0]),demoCase("demo-resume-case-ashu","阿树","demo-customer-ashu","2026-07-08",{...closedReported,outcome:"verified"},[resumeEvidence("demo-resume-feedback-ashu","feedback","feedback_received","收到简历投递结果","verified")],resumeChannels[0]),demoCase("demo-resume-case-qixi","七喜","demo-customer-qixi","2026-06-02",closedReported,[resumeEvidence("demo-resume-feedback-qixi","feedback","feedback_received","老客户再次购买简历优化","self_reported")],resumeChannels[1]),demoCase("demo-resume-case-nanfeng","南风","demo-customer-nanfeng","2026-05-12",{commercial:"cancelled",delivery:"not_started",payment:"unknown",outcome:"unknown",updatedAt:now},[resumeEvidence("demo-resume-lost-nanfeng","conversation","lead_created","识别交期导致的流失")],resumeChannels[0])]};
  const due = new Date(); due.setDate(due.getDate()+3); const dueDate = due.toISOString().slice(0,10);
  const refs = ["evidence:demo-inquiry","evidence:demo-delivery","evidence:demo-feedback","evidence:demo-feedback-linyan","evidence:demo-feedback-chen","evidence:demo-outcome-su"];
  const action = (id:string,channel:GrowthActionChannel,title:string,reason:string,goal:string,successMetric:string,assetTitle:string,assetContent:string,evidenceRefs:string[]):GrowthAction => ({id,title,channel,reason,goal,dueDate,successMetric,status:"ready",assetTitle,assetContent,evidenceRefs,updatedAt:now});
  const evidenceByChannel:Record<GrowthActionChannel,string[]> = {xianyu:refs.slice(0,3),xiaohongshu:refs,wechat:["evidence:demo-feedback","evidence:demo-feedback-linyan"]};
  const plan:GrowthPlan = {id:"demo-growth-plan",serviceId,weekOf:new Date().toISOString().slice(0,10),objective:interviewGrowthDemo.diagnosis.objective,diagnosisTitle:interviewGrowthDemo.diagnosis.title,diagnosisBody:interviewGrowthDemo.diagnosis.body,evidenceRefs:refs,createdAt:now,updatedAt:now,actions:interviewGrowthDemo.actions.map((item) => action(item.id,item.channel as GrowthActionChannel,item.title,item.reason,item.goal,item.successMetric,item.assetTitle,item.assetContent,evidenceByChannel[item.channel as GrowthActionChannel]))};
  const customer=(id:string,name:string,source="微信"):CustomerEntity=>({id,primaryName:name,identities:[{id:`demo-id-${id}`,label:name,source,normalizedLabel:normalizeCustomerName(name),confirmed:true,createdAt:now}],createdAt:now,updatedAt:now});
  writeBusinessMemory({services:[service,resumeService],customers:[{id:customerId,primaryName:"小鱼",identities:[{id:"demo-id-yitiao",label:"一条",source:"微信",normalizedLabel:"一条",confirmed:true,createdAt:now},{id:"demo-id-xiaoyu",label:"小鱼",source:"腾讯会议",normalizedLabel:"小鱼",confirmed:true,createdAt:now}],createdAt:now,updatedAt:now},customer("demo-customer-linyan","林言"),customer("demo-customer-zhou","周然","小红书"),customer("demo-customer-chen","陈默","闲鱼"),customer("demo-customer-su","苏晴"),customer("demo-customer-fang","方屿","转介绍"),customer("demo-customer-xu","许澄","闲鱼"),customer("demo-customer-xiaoman","小满","闲鱼"),customer("demo-customer-ashu","阿树","闲鱼"),customer("demo-customer-qixi","七喜"),customer("demo-customer-nanfeng","南风","闲鱼")],growthPlans:[plan]});
  localStorage.setItem(demoVersionKey,String(interviewGrowthDemo.version));
  return {serviceId,caseId,planId:plan.id};
}
