/**
 * Be Water competition demo data.
 *
 * This is deliberately plain front-end JavaScript so the demo scenario can be
 * edited without touching the extraction or growth-domain implementation.
 */
export const interviewGrowthDemo = {
  version: 6,
  enabledByDefault: true,
  scenario: "interview-growth-loop",
  service: {
    name: "模拟面试",
    description: "针对有工作经验的求职者进行项目深挖与表达诊断",
    price: 399,
    effortMinutes: 90,
    channels: ["闲鱼", "小红书", "微信"],
  },
  secondaryService: {
    name: "简历优化",
    description: "帮助有工作经验的求职者梳理岗位定位、项目贡献与结果表达",
    price: 299,
    effortMinutes: 120,
    channels: ["闲鱼", "微信"],
  },
  customers: [
    {primaryName: "小鱼", identities: [{label: "一条", source: "微信"}, {label: "小鱼", source: "腾讯会议"}]},
    {primaryName: "林言", identities: [{label: "林言", source: "微信"}]},
  ],
  records: [
    {
      id: "demo-inquiry",
      customer: "小鱼",
      kind: "咨询与预约",
      rawText: "一条：我工作两年了，但面试一追问项目细节就不知道怎么讲。想约一次模拟面试，周三晚上可以吗？\n我：可以，主要会围绕你的项目经历深挖，结束后给你表达建议。",
      summary: "客户因项目表达困难咨询并预约模拟面试。",
      evidence: ["一追问项目细节就不知道怎么讲", "想约一次模拟面试"],
    },
    {
      id: "demo-delivery",
      customer: "小鱼",
      kind: "模拟面试交付",
      rawText: "腾讯会议参会人：小鱼。面试官围绕项目背景、个人职责、技术取舍和业务结果连续追问。小鱼在个人贡献和结果量化部分多次停顿。复盘时重新组织为：问题—行动—取舍—结果。",
      summary: "交付重点是深挖项目并定位表达短板。",
      evidence: ["在个人贡献和结果量化部分多次停顿", "问题—行动—取舍—结果"],
    },
    {
      id: "demo-feedback",
      customer: "小鱼",
      kind: "客户反馈",
      rawText: "小鱼：这次最有帮助的不是模拟了一遍题，而是你一直追问项目，让我发现之前根本没讲清自己的贡献。现在知道该按什么结构准备了。",
      summary: "客户确认核心收获是项目深挖和表达结构。",
      evidence: ["最有帮助的不是模拟了一遍题", "发现之前根本没讲清自己的贡献"],
    },
    {
      id: "demo-feedback-linyan",
      customer: "林言",
      kind: "第二位客户反馈",
      rawText: "林言：以前总以为多刷题就行，这次把项目追问一遍，才发现业务结果和个人贡献都说得太虚。",
      summary: "第二个独立案例再次出现项目贡献表达问题。",
      evidence: ["业务结果和个人贡献都说得太虚"],
    },
    {
      id: "demo-inquiry-zhou",
      customer: "周然",
      kind: "小红书咨询",
      rawText: "周然：看了你写的项目表达帖子。我面试经常被问‘你具体负责什么’，但不知道这项服务最后会给我什么，也不太确定 399 元包含哪些内容。",
      summary: "内容带来咨询，但服务范围和交付内容不清晰阻碍预约。",
      evidence: ["不知道这项服务最后会给我什么", "不太确定 399 元包含哪些内容"],
    },
    {
      id: "demo-feedback-chen",
      customer: "陈默",
      kind: "交付反馈",
      rawText: "陈默：以前每次讲项目都从背景开始说很久。你追问后我才发现，面试官想听的是我的判断、取舍和结果。重写以后两分钟就能讲清楚。",
      summary: "第三个案例验证了项目表达结构的直接价值。",
      evidence: ["面试官想听的是我的判断、取舍和结果", "两分钟就能讲清楚"],
    },
    {
      id: "demo-outcome-su",
      customer: "苏晴",
      kind: "真实结果回访",
      rawText: "苏晴：昨天真实面试用了我们整理的项目结构，面试官追问了技术取舍，我能按当时练的逻辑答下来，已经进二面了。",
      summary: "客户在真实面试中使用表达结构并进入下一轮。",
      evidence: ["用了我们整理的项目结构", "已经进二面了"],
    },
    {
      id: "demo-referral-fang",
      customer: "方屿",
      kind: "转介绍成交",
      rawText: "方屿：苏晴把你推荐给我的。她说你不是陪着过题，而是会把项目一直问到讲清楚。我下周有面试，想直接约一次。",
      summary: "老客户用“把项目问到讲清楚”完成转介绍。",
      evidence: ["不是陪着过题", "把项目一直问到讲清楚"],
    },
    {
      id: "demo-lost-xu",
      customer: "许澄",
      kind: "闲鱼未成交咨询",
      rawText: "许澄：我主要想练算法题，如果只是深挖项目可能不太适合我，先不约了。",
      summary: "需求以算法练习为主，与项目表达诊断不匹配。",
      evidence: ["主要想练算法题", "深挖项目可能不太适合我"],
    },
    {
      id: "demo-resume-inquiry-xiaoman",
      customer: "小满",
      kind: "简历咨询",
      rawText: "小满：工作三年想换产品经理，但简历写得像岗位职责清单。投了十几份只有一次回复，想知道是不是项目没有写出成果。",
      summary: "客户因简历缺少项目成果和个人贡献表达而咨询。",
      evidence: ["写得像岗位职责清单", "投了十几份只有一次回复"],
    },
    {
      id: "demo-resume-feedback-ashu",
      customer: "阿树",
      kind: "简历交付反馈",
      rawText: "阿树：改完后最大的变化是每段经历都能看出我解决了什么问题，不再只是堆技术名词。昨天投的岗位已经收到面试邀请。",
      summary: "客户确认问题—行动—结果结构提升了简历可读性，并获得面试邀请。",
      evidence: ["每段经历都能看出我解决了什么问题", "已经收到面试邀请"],
    },
    {
      id: "demo-resume-feedback-qixi",
      customer: "七喜",
      kind: "简历复购反馈",
      rawText: "七喜：去年你帮我改完校招简历拿到了 offer，这次社招还是想找你。现在最需要的是把这一年的项目写出业务价值。",
      summary: "老客户复购，并再次提出项目业务价值表达需求。",
      evidence: ["改完校招简历拿到了 offer", "把这一年的项目写出业务价值"],
    },
    {
      id: "demo-resume-lost-nanfeng",
      customer: "南风",
      kind: "简历未成交咨询",
      rawText: "南风：我今晚就要投递，只想简单润色一下措辞。两天交付可能来不及，这次先自己改了。",
      summary: "客户因交付时效不匹配没有成交。",
      evidence: ["今晚就要投递", "两天交付可能来不及"],
    },
  ],
  diagnosis: {
    title: "客户真正购买的不是“模拟一遍”，而是“项目表达诊断”。",
    body: "两位客户都提到项目追问暴露了个人贡献、业务结果和表达结构问题。当前服务价值已在交付中被验证，但尚未清楚体现在对外介绍里。",
    objective: "本周获取 3 个模拟面试咨询，并验证“项目表达诊断”卖点。",
  },
  notebookAnalyses: {
    "demo-service-interview": {
      summary: "Bee 比较了模拟面试的 7 个案例与 9 条经营事实。项目表达已经从单次反馈变成跨客户重复出现的价值线索。",
      observations: [
        {
          kind: "pattern",
          title: "“项目表达诊断”正在跨客户重复出现",
          body: "小鱼、林言和陈默都在项目追问中暴露了个人贡献、业务结果或表达结构问题；交付后的收获也集中在把项目讲清楚，而不是多模拟一遍题。",
          confidence: "supported",
          sourceRefs: ["evidence:demo-delivery", "evidence:demo-feedback", "evidence:demo-feedback-linyan", "evidence:demo-feedback-chen"],
        },
        {
          kind: "observation",
          title: "真实面试结果开始验证交付价值",
          body: "苏晴在真实面试中使用整理后的项目结构，并进入二面。这是一条结果证据，说明表达结构不只带来主观感受，也可能改善真实面试表现。",
          confidence: "emerging",
          sourceRefs: ["evidence:demo-outcome-su", "evidence:demo-feedback"],
        },
        {
          kind: "content_move",
          title: "把“模拟面试”改写为“项目表达诊断”",
          body: "对外介绍应明确展示项目深挖、个人贡献定位、技术取舍和结果表达四项交付，同时写清 399 元包含的内容，减少咨询后的犹豫。",
          confidence: "supported",
          sourceRefs: ["evidence:demo-inquiry", "evidence:demo-inquiry-zhou", "evidence:demo-referral-fang"],
        },
      ],
    },
    "demo-service-resume": {
      summary: "Bee 比较了简历优化的 4 个案例与 4 条经营事实。客户反复购买的是把岗位职责改写成可验证的项目价值。",
      observations: [
        {
          kind: "pattern",
          title: "“写出项目成果”是简历优化的核心价值",
          body: "咨询者的问题不是缺少经历，而是简历像职责清单，无法体现解决的问题、个人贡献和业务结果；交付反馈也指向同一变化。",
          confidence: "supported",
          sourceRefs: ["evidence:demo-resume-inquiry-xiaoman", "evidence:demo-resume-feedback-ashu", "evidence:demo-resume-feedback-qixi"],
        },
        {
          kind: "observation",
          title: "结果证据与老客户复购同时出现",
          body: "阿树改写后获得面试邀请，七喜则因为过去获得 offer 再次购买。这两条线索说明“项目价值表达”既能形成结果证明，也具有复购潜力。",
          confidence: "emerging",
          sourceRefs: ["evidence:demo-resume-feedback-ashu", "evidence:demo-resume-feedback-qixi"],
        },
        {
          kind: "content_move",
          title: "增加加急边界，避免交付时效造成流失",
          body: "已有客户因为当晚投递、两天交付来不及而放弃。服务页应直接写明标准交付时间，并说明是否提供加急版本及对应价格。",
          confidence: "emerging",
          sourceRefs: ["evidence:demo-resume-lost-nanfeng", "service:demo-service-resume"],
        },
      ],
    },
  },
  actions: [
    {
      id: "demo-action-xianyu",
      channel: "xianyu",
      title: "优化闲鱼服务页",
      reason: "现有服务名称只描述形式，没有表达客户获得的具体变化。",
      goal: "提高服务页咨询率",
      successMetric: "7 天内获得 3 个有效咨询",
      assetTitle: "项目表达诊断｜有经验求职者模拟面试",
      assetContent: "工作两年，项目还是讲不清楚？\n\n这不是一场让你背答案的模拟面试。我会围绕你的真实项目持续追问，帮你找到：\n1. 个人贡献说不清的位置\n2. 技术取舍缺少依据的位置\n3. 业务结果无法量化的位置\n\n你将获得：60 分钟项目深挖 + 表达结构诊断 + 一份针对性准备清单。\n\n适合：有 1–5 年经验、简历能过但项目面经常卡住的求职者。",
    },
    {
      id: "demo-action-xhs",
      channel: "xiaohongshu",
      title: "发布项目表达痛点内容",
      reason: "咨询与交付反馈都反复出现“项目被追问就讲不清”。",
      goal: "吸引同类求职者主动咨询",
      successMetric: "曝光 1000，收藏 20，咨询 3",
      assetTitle: "工作两年，为什么项目还是讲不清楚？",
      assetContent: "很多人准备面试时一直刷题，却忽略了最容易被追问的项目。\n\n真正让回答失控的通常不是技术点，而是三件事：\n• 说不清自己到底做了什么\n• 解释不了为什么这样取舍\n• 讲不出结果对业务有什么影响\n\n我最近的模拟面试里，两位候选人都在项目深挖后发现：不是经历不够，而是表达没有结构。\n\n可以先用“问题—行动—取舍—结果”重写一个项目。想知道自己的项目会在哪里被追问，可以私信我“项目”。\n\n#面试 #求职 #项目经历 #模拟面试",
    },
    {
      id: "demo-action-wechat",
      channel: "wechat",
      title: "回访老客户并邀请转介绍",
      reason: "已完成服务的客户最清楚交付价值，也能补充真实面试结果。",
      goal: "获得结果反馈或转介绍",
      successMetric: "完成 3 次回访，获得 1 个转介绍",
      assetTitle: "模拟面试后续回访",
      assetContent: "嗨，最近面试进展怎么样？上次我们重点梳理了项目贡献和结果表达，我想了解哪些部分在真实面试里最有帮助。\n\n如果你身边也有人遇到“项目做过但讲不清”的问题，也欢迎把我这项项目表达诊断转给他。我会先帮他判断最需要准备的部分，不会直接推销。",
    },
  ],
  sampleResults: {
    "demo-action-xianyu": {impressions: 680, engagements: 18, inquiries: 4, bookings: 1, sales: 1, revenue: 399},
    "demo-action-xhs": {impressions: 3200, engagements: 48, inquiries: 6, bookings: 1, sales: 0, revenue: 0},
    "demo-action-wechat": {impressions: 3, engagements: 2, inquiries: 1, bookings: 1, sales: 1, revenue: 399},
  },
};
