import type {BusinessEvent,IdentityCandidate,OutcomeClaim,RawSourceKind} from "@/lib/domain/business-event";
import type {CaseStatusProposal,CaseStatus,DeliveryMaterial,ServiceAsset} from "@/lib/domain/delivery";

export type EvidenceType = "conversation" | "quote" | "delivery" | "feedback" | "note";
export type PricingMode = "session" | "hourly" | "package" | "retainer";
export type PlatformType = "xiaohongshu" | "xianyu" | "zhishixingqiu" | "wechat" | "douyin" | "offline" | "other";
export type ChannelStatus = "testing" | "active" | "paused";
export type ServiceChannel = {id:string;platform:PlatformType;customName?:string;launchedAt?:string;status:ChannelStatus};
export type ServiceStage = {id:string;type:EvidenceType;label?:string;origin?:"preset"|"custom"};
export type EvidenceAttachment = {name:string;dataUrl:string};
export type ExtractedFact = {label:string;value:string;confidence?:number};
export type BusinessEvidence = {id:string;type:EvidenceType;stageId?:string;content:string;createdAt:string;amount?:number;attachment?:EvidenceAttachment;extractionStatus?:"processing"|"ready"|"failed";extractionSummary?:string;extractedFacts?:ExtractedFact[];detectedSourceKind?:RawSourceKind;sourceHintConflict?:boolean;identityCandidates?:IdentityCandidate[];businessEvents?:BusinessEvent[];outcomeClaims?:OutcomeClaim[];caseStatusProposals?:CaseStatusProposal[];extractionVersion?:string};
export type ServiceCase = {id:string;customer:string;customerId?:string;purchaseNumber?:number;discoveryChannelId?:string;transactionChannelId?:string;discoveryChannel?:ServiceChannel;transactionChannel?:ServiceChannel;summary?:string;occurredAt?:string;createdAt:string;status:CaseStatus;stages?:ServiceStage[];materials?:DeliveryMaterial[];evidence:BusinessEvidence[]};
export type BusinessService = {id:string;name:string;description?:string;pricingMode?:PricingMode;price?:number;effortMinutes?:number;effort?:string;turnaroundDays?:number;turnaround?:string;channels?:ServiceChannel[];stages?:ServiceStage[];assets?:ServiceAsset[];createdAt:string;updatedAt?:string;cases:ServiceCase[]};
export type CustomerIdentity = {id:string;label:string;source?:string;normalizedLabel:string;confirmed:boolean;createdAt:string};
export type CustomerEntity = {id:string;primaryName:string;identities:CustomerIdentity[];createdAt:string;updatedAt:string};
export type GrowthActionChannel = "xianyu"|"xiaohongshu"|"wechat";
export type GrowthActionStatus = "planned"|"ready"|"published"|"measured";
export type GrowthMetrics = {impressions:number;engagements:number;inquiries:number;bookings:number;sales:number;revenue:number};
export type GrowthAction = {id:string;title:string;channel:GrowthActionChannel;reason:string;goal:string;dueDate:string;successMetric:string;status:GrowthActionStatus;assetTitle:string;assetContent:string;evidenceRefs:string[];metrics?:GrowthMetrics;resultNote?:string;updatedAt:string};
export type GrowthPlan = {id:string;serviceId:string;weekOf:string;objective:string;diagnosisTitle:string;diagnosisBody:string;evidenceRefs:string[];actions:GrowthAction[];revision?:{summary:string;continueActionIds:string[];adjustments:string[];nextActions:string[];generatedAt:string};createdAt:string;updatedAt:string};
export type BusinessMemoryModel = {services:BusinessService[];customers?:CustomerEntity[];growthPlans?:GrowthPlan[]};
export type CustomerHistory = {id:string;name:string;purchases:{caseId:string;serviceId:string;serviceName:string;occurredAt?:string;createdAt:string}[]};
