import type {BusinessMemoryModel,GrowthAction,PrototypeEvidence} from "./business-memory";
import type {PrototypeLocale} from "./ui-copy";

const names:Record<string,[string,string]> = {
  "一条":["一條","Yitiao"],"小鱼":["小魚","Xiaoyu"],"林言":["林言","Lin Yan"],"周然":["周然","Zhou Ran"],"陈默":["陳默","Chen Mo"],"苏晴":["蘇晴","Su Qing"],"方屿":["方嶼","Fang Yu"],"许澄":["許澄","Xu Cheng"],"小满":["小滿","Xiaoman"],"阿树":["阿樹","Ashu"],"七喜":["七喜","Qixi"],"南风":["南風","Nanfeng"],
};

const sources:Record<string,[string,string]> = {"微信":["微信","WeChat"],"腾讯会议":["騰訊會議","Tencent Meeting"],"小红书":["小紅書","Xiaohongshu"],"闲鱼":["閒魚","Xianyu"],"转介绍":["轉介紹","Referral"]};

type EvidenceTranslation={content:string;summary:string;snippets:string[]};
const evidenceEn:Record<string,EvidenceTranslation> = {
  "demo-inquiry":{content:"Yitiao: I have worked for two years, but when interviewers dig into project details, I do not know how to explain them. Can I book a mock interview for Wednesday evening?\nMe: Yes. We will focus on your real projects and finish with concrete storytelling feedback.",summary:"The client asked for and booked a mock interview because project storytelling was difficult.",snippets:["I do not know how to explain project details","Can I book a mock interview?"]},
  "demo-delivery":{content:"Tencent Meeting participant: Xiaoyu. The interviewer repeatedly asked about project context, personal responsibility, technical trade-offs, and business outcomes. Xiaoyu paused when quantifying personal contribution and results. The review reorganized the story as Problem — Action — Trade-off — Result.",summary:"Delivery focused on a project deep-dive and identifying storytelling gaps.",snippets:["Paused on personal contribution and quantified results","Problem — Action — Trade-off — Result"]},
  "demo-feedback":{content:"Xiaoyu: The most useful part was not answering another set of questions. Your project follow-ups showed me that I had never explained my contribution clearly. Now I know what structure to use.",summary:"The client confirmed that project deep-dives and storytelling structure were the core value.",snippets:["The most useful part was not another practice round","I had never explained my contribution clearly"]},
  "demo-feedback-linyan":{content:"Lin Yan: I used to think more question drills were enough. After the project follow-ups, I realized my business outcomes and personal contribution sounded vague.",summary:"A second client independently surfaced the same project-storytelling problem.",snippets:["Business outcomes and personal contribution sounded vague"]},
  "demo-inquiry-zhou":{content:"Zhou Ran: I read your project-storytelling post. Interviewers often ask what I specifically owned, but I do not know what this service delivers or what the ¥399 includes.",summary:"Content generated an inquiry, but unclear scope and deliverables blocked the booking.",snippets:["I do not know what this service delivers","What does the ¥399 include?"]},
  "demo-feedback-chen":{content:"Chen Mo: I used to spend too long on project background. Your follow-ups showed me that interviewers want my judgment, trade-offs, and results. After rewriting, I can explain it in two minutes.",summary:"A third case validated the direct value of a clearer project-story structure.",snippets:["Interviewers want judgment, trade-offs, and results","I can explain it in two minutes"]},
  "demo-outcome-su":{content:"Su Qing: I used our revised project structure in yesterday's real interview. I answered the technical trade-off follow-up with the logic we practiced and have advanced to round two.",summary:"The client used the new structure in a real interview and advanced to the next round.",snippets:["Used our revised project structure","Advanced to round two"]},
  "demo-referral-fang":{content:"Fang Yu: Su Qing recommended you. She said you do not just run through questions—you keep probing until the project is clear. I have an interview next week and want to book a session.",summary:"A former client referral converted through the promise of making projects clear.",snippets:["You do not just run through questions","You keep probing until the project is clear"]},
  "demo-lost-xu":{content:"Xu Cheng: I mainly want algorithm practice. If the session focuses on project deep-dives, it may not fit me, so I will not book for now.",summary:"The algorithm-practice need did not match the project-storytelling diagnostic.",snippets:["I mainly want algorithm practice","Project deep-dives may not fit me"]},
  "demo-resume-inquiry-xiaoman":{content:"Xiaoman: I have worked for three years and want to move into product management, but my resume reads like a duty list. I sent more than ten applications and received one reply. Are my project outcomes unclear?",summary:"The client asked for help because the resume did not show project outcomes or personal contribution.",snippets:["My resume reads like a duty list","More than ten applications produced one reply"]},
  "demo-resume-feedback-ashu":{content:"Ashu: After the rewrite, every experience shows the problem I solved instead of listing technical terms. An application I sent yesterday already produced an interview invitation.",summary:"A Problem — Action — Result structure improved readability and produced an interview invitation.",snippets:["Every experience shows the problem I solved","Already received an interview invitation"]},
  "demo-resume-feedback-qixi":{content:"Qixi: Your campus-recruiting rewrite helped me get an offer last year, so I came back for this job search. I now need to show the business value of this year's projects.",summary:"A returning client again asked for stronger project-value storytelling.",snippets:["The previous rewrite helped me get an offer","Show the business value of this year's projects"]},
  "demo-resume-lost-nanfeng":{content:"Nanfeng: I need to apply tonight and only want a quick wording polish. A two-day turnaround is too late, so I will revise it myself this time.",summary:"The opportunity was lost because the delivery window did not fit the client's deadline.",snippets:["I need to apply tonight","A two-day turnaround is too late"]},
};

const evidenceTw:Record<string,EvidenceTranslation> = Object.fromEntries(Object.entries({
  "demo-inquiry":["一條：我工作兩年了，但面試一追問專案細節就不知道怎麼講。想約一次模擬面試，週三晚上可以嗎？\n我：可以，主要會圍繞你的專案經歷深挖，結束後給你表達建議。","客戶因專案表達困難諮詢並預約模擬面試。"],
  "demo-delivery":["騰訊會議參與者：小魚。面試官圍繞專案背景、個人職責、技術取捨和業務結果連續追問。小魚在個人貢獻和結果量化部分多次停頓，複盤時重新組織為：問題—行動—取捨—結果。","交付重點是深挖專案並定位表達短板。"],
  "demo-feedback":["小魚：最有幫助的不是多模擬一遍題，而是你一直追問專案，讓我發現之前根本沒講清自己的貢獻。現在知道該按什麼結構準備了。","客戶確認核心收穫是專案深挖和表達結構。"],
  "demo-feedback-linyan":["林言：以前總以為多刷題就行，這次把專案追問一遍，才發現業務結果和個人貢獻都說得太虛。","另一位客戶也回饋專案追問暴露了表達問題。"],
  "demo-inquiry-zhou":["周然：看了你寫的專案表達貼文。我面試經常被問「你具體負責什麼」，但不知道服務最後會給我什麼，也不確定 399 元包含哪些內容。","內容帶來諮詢，但服務範圍和交付內容不清晰阻礙預約。"],
  "demo-feedback-chen":["陳默：以前每次講專案都從背景開始說很久。你追問後我才發現，面試官想聽的是我的判斷、取捨和結果。重寫後兩分鐘就能講清楚。","第三個案例驗證了專案表達結構的直接價值。"],
  "demo-outcome-su":["蘇晴：昨天真實面試用了我們整理的專案結構，面試官追問技術取捨時，我能按練習的邏輯回答，已經進二面了。","客戶在真實面試中使用表達結構並進入下一輪。"],
  "demo-referral-fang":["方嶼：蘇晴把你推薦給我。她說你不是陪著過題，而是會把專案一直問到講清楚。我下週有面試，想直接預約一次。","老客戶用「把專案問到講清楚」完成轉介紹。"],
  "demo-lost-xu":["許澄：我主要想練演算法題，如果只是深挖專案可能不太適合我，先不約了。","需求以演算法練習為主，與專案表達診斷不匹配。"],
  "demo-resume-inquiry-xiaoman":["小滿：工作三年想轉產品經理，但履歷寫得像職責清單。投了十幾份只有一次回覆，想知道是不是專案沒有寫出成果。","客戶因履歷缺少專案成果和個人貢獻表達而諮詢。"],
  "demo-resume-feedback-ashu":["阿樹：改完後每段經歷都能看出我解決了什麼問題，不再只是堆技術名詞。昨天投的職缺已經收到面試邀請。","問題—行動—結果結構提升了履歷可讀性，並帶來面試邀請。"],
  "demo-resume-feedback-qixi":["七喜：去年你幫我改完校招履歷拿到 offer，這次社招還是想找你。現在最需要的是把這一年的專案寫出業務價值。","老客戶再次購買，並再次提出專案業務價值表達需求。"],
  "demo-resume-lost-nanfeng":["南風：我今晚就要投遞，只想簡單潤飾措辭。兩天交付可能來不及，這次先自己改了。","客戶因交付時效不匹配而未成交。"],
}).map(([id,[content,summary]])=>[id,{content,summary,snippets:[summary]}]));

const actionEn:Record<string,Partial<GrowthAction>>={
  "demo-action-xianyu":{title:"Optimize the Xianyu service page",reason:"The current name describes the format, not the concrete client outcome.",goal:"Increase qualified service-page inquiries",successMetric:"Receive 3 qualified inquiries within 7 days",assetTitle:"Project Storytelling Diagnostic | Mock Interview for Experienced Candidates",assetContent:"Worked for two years but still struggle to explain your projects?\n\nThis is not another answer-drill session. We will probe your real projects to identify unclear personal contribution, unsupported technical trade-offs, and unquantified business outcomes.\n\nYou receive a 60-minute project deep-dive, a storytelling diagnosis, and a focused preparation checklist."},
  "demo-action-xiaohongshu":{title:"Publish content about project-storytelling pain",reason:"Both inquiries and delivery feedback repeatedly mention losing clarity under project follow-ups.",goal:"Attract similar candidates to inquire",successMetric:"1,000 impressions, 20 saves, and 3 inquiries",assetTitle:"Two years into work—why are your projects still hard to explain?",assetContent:"Many candidates keep drilling questions while ignoring the project stories interviewers probe most.\n\nAnswers usually break down because personal contribution is unclear, trade-offs lack reasoning, or business outcomes are missing.\n\nTry rewriting one project as Problem — Action — Trade-off — Result. Message “project” if you want to know where interviewers may challenge your story."},
  "demo-action-wechat":{title:"Follow up with past clients and invite referrals",reason:"Past clients understand the delivery value and can add real interview outcomes.",goal:"Collect outcome feedback or a referral",successMetric:"Complete 3 follow-ups and receive 1 referral",assetTitle:"Post-interview follow-up",assetContent:"Hi—how have your interviews been going? We focused on personal contribution and outcome storytelling last time, and I would love to know what helped most in a real interview.\n\nIf someone around you also struggles to explain projects they have actually done, feel free to share this diagnostic with them. I will first help them decide whether it fits."},
};

const actionTw:Record<string,Partial<GrowthAction>>={
  "demo-action-xianyu":{title:"優化閒魚服務頁",reason:"目前服務名稱只描述形式，沒有表達客戶獲得的具體變化。",goal:"提高服務頁諮詢率",successMetric:"7 天內獲得 3 個有效諮詢",assetTitle:"專案表達診斷｜有經驗求職者模擬面試",assetContent:"工作兩年，專案還是講不清楚？\n\n這不是一場讓你背答案的模擬面試。我會圍繞真實專案持續追問，找出個人貢獻、技術取捨與業務結果的表達缺口。\n\n你將獲得 60 分鐘專案深挖、表達結構診斷和一份準備清單。"},
  "demo-action-xiaohongshu":{title:"發布專案表達痛點內容",reason:"諮詢與交付回饋都反覆出現「專案被追問就講不清」。",goal:"吸引同類求職者主動諮詢",successMetric:"曝光 1000、收藏 20、諮詢 3",assetTitle:"工作兩年，為什麼專案還是講不清楚？",assetContent:"很多人準備面試時一直刷題，卻忽略最容易被追問的專案。\n\n真正讓回答失控的通常是個人貢獻、技術取捨和業務結果缺少結構。可以先用「問題—行動—取捨—結果」重寫一個專案。"},
  "demo-action-wechat":{title:"回訪老客戶並邀請轉介紹",reason:"已完成服務的客戶最清楚交付價值，也能補充真實面試結果。",goal:"獲得結果回饋或轉介紹",successMetric:"完成 3 次回訪，獲得 1 個轉介紹",assetTitle:"模擬面試後續回訪",assetContent:"嗨，最近面試進展怎麼樣？上次我們重點梳理了專案貢獻和結果表達，想了解哪些部分在真實面試裡最有幫助。\n\n如果身邊也有人遇到「專案做過但講不清」的問題，也歡迎把這項診斷分享給他。"},
};

function translatedEvidence(entry:PrototypeEvidence,locale:PrototypeLocale):PrototypeEvidence {
  const translated=(locale==="en-US"?evidenceEn:evidenceTw)[entry.id];
  if (!translated) return entry;
  const eventNames=locale==="en-US"?{lead_created:"Inquiry received",booking_confirmed:"Booking confirmed",delivery_started:"Delivery started",delivery_completed:"Delivery completed",feedback_received:"Feedback received"}:{lead_created:"收到諮詢",booking_confirmed:"確認預約",delivery_started:"開始交付",delivery_completed:"完成交付",feedback_received:"收到回饋"};
  return {...entry,content:translated.content,extractionSummary:translated.summary,identityCandidates:entry.identityCandidates?.map((item)=>({...item,displayName:localName(item.displayName,locale),source:localSource(item.source,locale) ?? null,evidence:translated.snippets[0]})),businessEvents:entry.businessEvents?.map((event)=>({...event,title:eventNames[event.type as keyof typeof eventNames] ?? (locale==="en-US"?"Business event":"經營事件"),summary:translated.summary,evidence:translated.snippets,nextActions:event.nextActions.length?[locale==="en-US"?"Continue with the next confirmed step":"繼續下一個已確認步驟"]:[]})),outcomeClaims:entry.outcomeClaims?.map((claim)=>({...claim,theme:locale==="en-US"?"Project storytelling":"專案表達",statement:translated.summary,evidence:translated.snippets[0]}))};
}

function localName(value:string,locale:PrototypeLocale){return locale==="zh-CN"?value:(names[value]?.[locale==="en-US"?1:0]??value);}
function localSource(value:string|null|undefined,locale:PrototypeLocale){if(!value||locale==="zh-CN")return value;return sources[value]?.[locale==="en-US"?1:0]??value;}

export function localizeMockModel(model:BusinessMemoryModel,locale:PrototypeLocale):BusinessMemoryModel {
  if(locale==="zh-CN"||!model.services.some((service)=>service.id.startsWith("demo-service-"))) return model;
  const en=locale==="en-US";
  const actions=en?actionEn:actionTw;
  return {...model,services:model.services.map((service)=>service.id.startsWith("demo-service-")?{...service,name:service.id==="demo-service-interview"?(en?"Mock Interview":"模擬面試"):(en?"Resume Optimization":"履歷優化"),description:service.id==="demo-service-interview"?(en?"Project deep-dives and storytelling diagnostics for experienced candidates":"為有工作經驗的求職者進行專案深挖與表達診斷"):(en?"Clarify role positioning, project contribution, and outcome storytelling":"協助有工作經驗的求職者梳理職位定位、專案貢獻與結果表達"),cases:service.cases.map((item)=>({...item,customer:localName(item.customer,locale),evidence:item.evidence.map((entry)=>translatedEvidence(entry,locale))}))}:service),customers:model.customers?.map((customer)=>({...customer,primaryName:localName(customer.primaryName,locale),identities:customer.identities.map((identity)=>({...identity,label:localName(identity.label,locale),source:localSource(identity.source,locale) ?? undefined}))})),growthPlans:model.growthPlans?.map((plan)=>plan.id==="demo-growth-plan"?{...plan,objective:en?'Get 3 mock-interview inquiries this week and test the “Project Storytelling Diagnostic” positioning.':'本週獲得 3 個模擬面試諮詢，並驗證「專案表達診斷」賣點。',diagnosisTitle:en?'Clients are not buying “one practice round”—they are buying a Project Storytelling Diagnostic.':'客戶真正購買的不是「模擬一遍」，而是「專案表達診斷」。',diagnosisBody:en?'Multiple clients exposed gaps in personal contribution, business outcomes, and storytelling structure under project follow-ups. Delivery has validated the value, but the public service description does not yet make it clear.':'多位客戶都在專案追問中暴露個人貢獻、業務結果和表達結構問題。交付已驗證這項價值，但對外介紹仍不夠清楚。',actions:plan.actions.map((action)=>({...action,...actions[action.id]})),revision:plan.revision?{...plan.revision,summary:en?'This round has produced measurable inquiries, bookings, and sales. Continue the strongest action and clarify the service scope.':'本輪已產生可衡量的諮詢、預約與成交。下一輪繼續最有效的行動，並補清楚服務範圍。',adjustments:[en?'Add the delivery checklist, price, and case proof to improve inquiry-to-sale conversion.':'補充交付清單、價格與案例證明，提高諮詢到成交的轉化。'],nextActions:[en?'Reuse the strongest positioning with a clear delivery checklist.':'沿用最有效的定位，加入清楚的交付清單。',en?'Follow up with inquiries that did not book.':'回訪尚未預約的諮詢者。',en?'Keep recording inquiries, bookings, and sales by channel.':'持續按渠道記錄諮詢、預約與成交。']} : undefined}:plan)};
}
