"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, GripVertical, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { makeWorkflow, type ServiceTemplate, type WorkflowStep } from "@/lib/domain/service";

export function ServiceCreator() {
  const router = useRouter();
  const [phase, setPhase] = useState<1|2>(1);
  const [name,setName]=useState(""); const [price,setPrice]=useState(""); const [days,setDays]=useState("3");
  const [hours,setHours]=useState(""); const [revisions,setRevisions]=useState("1");
  const [included,setIncluded]=useState("一份简历修改\n一次 30 分钟讲解\n一轮反馈调整"); const [excluded,setExcluded]=useState("模拟面试\n职业方向深度咨询\n无限次修改");
  const [steps,setSteps]=useState<WorkflowStep[]>(makeWorkflow());
  const update=(id:string,patch:Partial<WorkflowStep>)=>setSteps(steps.map(s=>s.id===id?{...s,...patch}:s));
  function save(){const now=new Date().toISOString();const service:ServiceTemplate={id:crypto.randomUUID(),name,defaultPrice:Number(price)||undefined,defaultDeliveryDays:Number(days)||undefined,defaultWorkloadHours:Number(hours)||undefined,defaultRevisionCount:Number(revisions)||undefined,included:included.split("\n").map(x=>x.trim()).filter(Boolean),excluded:excluded.split("\n").map(x=>x.trim()).filter(Boolean),workflow:steps,createdAt:now,updatedAt:now};const all=JSON.parse(localStorage.getItem("bewater_services")??"[]");all.unshift(service);localStorage.setItem("bewater_services",JSON.stringify(all));localStorage.setItem("bewater_service_toast",service.name);router.push("/workspace");}
  return <main className="min-h-dvh lg:ml-[224px]"><div className="mx-auto max-w-[920px] px-5 pb-16 pt-20 sm:px-8 lg:px-12 lg:pt-20"><Link href="/workspace/services" className="inline-flex items-center gap-1.5 text-xs text-[var(--muted)]"><ArrowLeft className="size-3.5"/>返回服务</Link>
    <div className="mt-8 flex items-center gap-3 text-xs"><span className={`grid size-7 place-items-center rounded-full ${phase===1?"bg-[var(--brand)] text-white":"bg-[var(--brand-soft)] text-[var(--brand)]"}`}>{phase===1?1:<Check className="size-4"/>}</span><span className="h-px w-12 bg-[var(--line-strong)]"/><span className={`grid size-7 place-items-center rounded-full ${phase===2?"bg-[var(--brand)] text-white":"bg-white text-[var(--subtle)]"}`}>2</span><span className="ml-1 text-[var(--muted)]">{phase===1?"服务基准":"标准流程"}</span></div>
    {phase===1?<section className="mt-9"><p className="text-xs font-semibold tracking-[.12em] text-[var(--brand)]">建立共同基准</p><h1 className="page-title mt-3">你正在提供什么服务？</h1><p className="mt-3 text-sm leading-7 text-[var(--muted)]">先建立一个轻量基准。以后每个案例都会继承它，你只需要修改本次不同的部分。</p><div className="mt-9 rounded-[24px] bg-white/65 p-6 shadow-[0_20px_60px_rgba(72,111,125,.07)] sm:p-8"><Field label="服务名称 *" value={name} onChange={setName} placeholder="例如：简历修改"/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="默认价格（元）" type="number" value={price} onChange={setPrice}/><Field label="标准交期（天）" type="number" value={days} onChange={setDays}/><Field label="预计投入时间（小时）" type="number" value={hours} onChange={setHours}/><Field label="默认修改次数" type="number" value={revisions} onChange={setRevisions}/></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Area label="通常包含哪些内容？" value={included} onChange={setIncluded}/><Area label="通常不包含哪些内容？（可选）" value={excluded} onChange={setExcluded}/></div></div><button disabled={!name.trim()} onClick={()=>setPhase(2)} className="mt-7 inline-flex h-11 items-center gap-2 rounded-xl bg-[var(--brand)] px-5 text-sm font-semibold text-white disabled:opacity-40">下一步：搭建流程<ArrowRight className="size-4"/></button></section>:
    <section className="mt-9"><p className="text-xs font-semibold tracking-[.12em] text-[var(--brand)]">{name} · 建议模板</p><h1 className="page-title mt-3">这项服务通常怎样完成？</h1><p className="mt-3 text-sm leading-7 text-[var(--muted)]">这里定义的是标准过程。具体案例可以跳过、重复或新增步骤，Bee 会记录这些差异。</p><div className="mt-8 space-y-3">{steps.map((step,index)=><details key={step.id} className="group rounded-2xl border border-[var(--line)] bg-white/65 p-4" open={index===0}><summary className="flex cursor-pointer list-none items-center gap-3"><GripVertical className="size-4 text-[var(--subtle)]"/><span className="w-7 text-xs text-[var(--subtle)]">{String(index+1).padStart(2,"0")}</span><input aria-label="步骤名称" value={step.name} onClick={e=>e.stopPropagation()} onChange={e=>update(step.id,{name:e.target.value})} className="h-9 flex-1 bg-transparent text-sm font-semibold outline-none"/><span className="rounded-full bg-[var(--brand-soft)] px-2.5 py-1 text-[10px] text-[var(--brand-dark)]">{step.required?"必需":"可选"}</span></summary><div className="ml-14 mt-4 grid gap-4 border-t border-[var(--line)] pt-4 sm:grid-cols-2"><Field label="这一步通常需要什么记录？" value={step.recordType} onChange={v=>update(step.id,{recordType:v})}/><Field label="怎样算完成？" value={step.completionCondition} onChange={v=>update(step.id,{completionCondition:v})}/><label className="flex items-center gap-2 text-xs text-[var(--muted)]"><input type="checkbox" checked={step.required} onChange={e=>update(step.id,{required:e.target.checked})}/>设为必需步骤</label><button onClick={()=>setSteps(steps.filter(s=>s.id!==step.id))} className="inline-flex items-center justify-self-end gap-1 text-xs text-[var(--danger)]"><Trash2 className="size-3.5"/>删除步骤</button></div></details>)}</div><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>setSteps([...steps,...makeWorkflow(["新步骤"])])} className="inline-flex h-11 items-center gap-2 rounded-xl border border-[var(--line-strong)] bg-white px-4 text-sm font-semibold"><Plus className="size-4"/>添加步骤</button><button onClick={save} disabled={!steps.length} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[var(--brand)] px-5 text-sm font-semibold text-white"><Check className="size-4"/>保存服务流程</button></div></section>}
  </div></main>;
}
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="grid gap-2 text-xs text-[var(--muted)]">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-11 rounded-xl border border-[var(--line)] bg-white/75 px-3 text-sm text-[var(--ink)] outline-none focus:border-[#7fa8b5] focus:ring-4 focus:ring-[var(--focus)]"/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-xs text-[var(--muted)]">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} rows={5} className="resize-none rounded-xl border border-[var(--line)] bg-white/75 p-3 text-sm leading-7 text-[var(--ink)] outline-none focus:border-[#7fa8b5]"/></label>}
